stages:
  - build
  - test
  - archive
  - deploy

build_project:
  stage: build
  tags:
    - ios_16-4
    - xcode_14-2
    - macos_13-3-1
  script:
    - xcodebuild clean build test -project /Users/juan.merlos/Desktop/EssentialDevloper_MASTER/EssentialFeed/EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  os: osx
  osx_image: xcode14.2

archive_project:
  stage: archive
  script:
    - xcodebuild clean archive -archivePath build/ProjectName -scheme SchemeName
    - xcodebuild -exportArchive -exportFormat ipa -archivePath "build/ProjectName.xcarchive" -exportPath "build/ProjectName.ipa" -exportProvisioningProfile "ProvisioningProfileName"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - build/ProjectName.ipa
  tags:
    - ios_11-3
    - xcode_9-3
    - macos_10-13

deploy:
  stage: deploy
  script: echo "Define your deployment script!"
  environment: production
