os: osx
osx_image: xcode14.3
language: swift
script: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme CI -destination "$DESTINATION" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
