os: osx
osx_image: xcode14.2
language: swift
xcode_project: EssentialFeed.xcodeproj
xcode_scheme: CI
env:
  global:
    - SWIFT_VERSION=5.0
script:
  - xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" -destination "platform=macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
